CREATE TABLE `webcv`.`skills` ( `id` INT(2) UNSIGNED NOT NULL AUTO_INCREMENT , `Skill_Name` VARCHAR(30) NOT NULL , `Progress` INT(3) UNSIGNED NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `webcv`.`education` ( `id` INT(2) UNSIGNED NOT NULL AUTO_INCREMENT , `Title` VARCHAR(30) NOT NULL , `Shool` VARCHAR(30) NOT NULL , `Time` VARCHAR(30) NOT NULL , `Description` INT(255) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `webcv`.`interest` ( `id` INT(2) UNSIGNED NOT NULL AUTO_INCREMENT , `Interest` VARCHAR(20) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `webcv`.`experience` ( `id` INT(2) UNSIGNED NOT NULL AUTO_INCREMENT , `Title` VARCHAR(30) NOT NULL , `Work_Place` VARCHAR(30) NOT NULL , `Time` VARCHAR(30) NOT NULL , `Description` VARCHAR(255) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `webcv`.`projects` ( `id` INT(2) UNSIGNED NOT NULL AUTO_INCREMENT , `Title` VARCHAR(30) NOT NULL , `Time` VARCHAR(30) NOT NULL , `Description` VARCHAR(30) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `webcv`.`contact` ( `id` INT(2) UNSIGNED NOT NULL AUTO_INCREMENT , `Type` VARCHAR(20) NOT NULL , `Contact_Link` VARCHAR(100) NOT NULL , `Description` VARCHAR(30) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;