CREATE TABLE `id15929116_webcv`.`u_information` ( `id` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT , `Head_Title` VARCHAR(30) NOT NULL , `Name` VARCHAR(30) NOT NULL , `Job` VARCHAR(50) NOT NULL , `Profile_Image` VARCHAR(50) NOT NULL , `About_Me` VARCHAR(255) NOT NULL , `UserID` INT(3) UNSIGNED NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `id15929116_webcv`.`user` ( `id` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT , `Username` VARCHAR(30) NOT NULL , `Psword` VARCHAR(30) NOT NULL , `User_Level` BIT(1) NULL DEFAULT b'0' , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `id15929116_webcv`.`skills` ( `id` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT , `Skill_Name` VARCHAR(30) NOT NULL , `Progress` INT(3) UNSIGNED NOT NULL , `UserID` INT(3) UNSIGNED NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `id15929116_webcv`.`projects` ( `id` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT , `Title` VARCHAR(30) NOT NULL , `Project_Link` VARCHAR(100) NOT NULL , `Time` VARCHAR(30) NOT NULL , `Description` VARCHAR(255) NOT NULL , `UserID` INT(3) UNSIGNED NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `id15929116_webcv`.`languages` ( `id` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT , `Language` VARCHAR(30) NOT NULL , `Level` VARCHAR(20) NOT NULL , `UserID` INT(3) UNSIGNED NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `id15929116_webcv`.`interest` ( `id` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT , `Interest` VARCHAR(20) NOT NULL , `UserID` INT(3) UNSIGNED NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `id15929116_webcv`.`experience` ( `id` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT , `Title` VARCHAR(30) NOT NULL , `Work_Place` VARCHAR(30) NOT NULL , `Time` VARCHAR(30) NOT NULL , `Description` VARCHAR(255) NOT NULL , `UserID` INT(3) UNSIGNED NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `id15929116_webcv`.`education` ( `id` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT , `Title` VARCHAR(30) NOT NULL , `School` VARCHAR(30) NOT NULL , `Time` VARCHAR(30) NOT NULL , `Description` VARCHAR(255) NOT NULL , `UserID` INT(3) UNSIGNED NOT NULL , PRIMARY KEY (`id`), INDEX (`UserID`)) ENGINE = InnoDB;

CREATE TABLE `id15929116_webcv`.`contact` ( `id` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT , `Type` VARCHAR(20) NOT NULL , `Contact_Link` VARCHAR(100) NOT NULL , `Description` VARCHAR(30) NOT NULL , `UserID` INT(3) UNSIGNED NOT NULL , PRIMARY KEY (`id`), INDEX (`UserID`)) ENGINE = InnoDB;
